[SETTINGS]
input_dir = C:\ProgramData\NexSens\CONNECT\Tmp
output_dir = C:\Users\Seatronic\Documents\Data_Lexplore\WaveBuoy
backup_dir = C:\Users\Seatronic\Documents\Data_Lexplore\WaveBuoy_Backup\Tmp

; 1 = shows header / 0 = hides header
write_header = 0

[METADATA]
; 1 = shows / 0 = hides
Timestamp_Date = 1
Timestamp_Time = 1
Timestamp_Raw = 0
UUID = 0
Dev_NID = 0
Bin_Format = 0
Format_ID = 0

[PARAMETERS]
; add a ";" to disable. value will not appear in the output file.
;3  = Processor Power
;9  = RTC Power
;10 = Primary Power
;11 = Secondary Power
;12 = Sensor Power
;13 = Total System Current
;14 = Sensor Current
;15 = Internal Pressure ;not available anymore ?
;16 = Internal Temperature
;17 = Internal Humidity
;18 = Cell Signal Strength
;19 = Cell Status
20 = Heading
21 = HS Wave Height
22 = Tp (DPD) Wave Period
23 = Dominant Wave Direction
24 = Mean Wave Direction (MWD)
25 = Hmax Wave Height
26 = H10 Wave Height
27 = Te Energy Period
28 = Pitch
29 = Roll
;30 = Sample No ;not sure it works
